### ISSUE TITLE
python setup.py build develop    report errors   Command '['ninja', '-v']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by JD012** [yaorz97/PARENet#3]

**Comment by JD012** [comment]
**I don't have a GPU, so when I modify CUDAExtension to CppExtension in PARANet/setup. py, the compilation error is as follows**

`c++ -MMD -MF /workspace/PARENet/build/temp.linux-x86_64-3.10/pareconv/extensions/pybind.o.d -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -fPIC -I/torch/venv3/pytorch/lib/python3.10/site-packages/torch/include -I/torch/venv3/pytorch/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/torch/venv3/pytorch/lib/python3.10/site-packages/torch/include/TH -I/torch/venv3/pytorch/lib/python3.10/site-packages/torch/include/THC -I/torch/venv3/pytorch/include -I/opt/py3.10/include/python3.10 -c -c /workspace/PARENet/pareconv/extensions/pybind.cpp -o /workspace/PARENet/build/temp.linux-x86_64-3.10/pareconv/extensions/pybind.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
In file included from /workspace/PARENet/pareconv/extensions/cpu/radius_neighbors/../../common/torch_helper.h:3:0,
                 from /workspace/PARENet/pareconv/extensions/cpu/radius_neighbors/radius_neighbors.h:3,
                 from /workspace/PARENet/pareconv/extensions/pybind.cpp:3:
/torch/venv3/pytorch/lib/python3.10/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include <cuda_runtime_api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
[6/6] c++ -MMD -MF /workspace/PARENet/build/temp.linux-x86_64-3.10/pareconv/extensions/cpu/radius_neighbors/radius_neighbors_cpu.o.d -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -fPIC -I/torch/venv3/pytorch/lib/python3.10/site-packages/torch/include -I/torch/venv3/pytorch/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/torch/venv3/pytorch/lib/python3.10/site-packages/torch/include/TH -I/torch/venv3/pytorch/lib/python3.10/site-packages/torch/include/THC -I/torch/venv3/pytorch/include -I/opt/py3.10/include/python3.10 -c -c /workspace/PARENet/pareconv/extensions/cpu/radius_neighbors/radius_neighbors_cpu.cpp -o /workspace/PARENet/build/temp.linux-x86_64-3.10/pareconv/extensions/cpu/radius_neighbors/radius_neighbors_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/torch/venv3/pytorch/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
    subprocess.run(
  File "/opt/py3.10/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.`

**Comment by JD012** [comment]
**I don't have a GPU, so when I modify CUDAExtension to CppExtension in PARANet/setup. py, the compilation error is as follows**

`c++ -MMD -MF /workspace/PARENet/build/temp.linux-x86_64-3.10/pareconv/extensions/pybind.o.d -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -fPIC -I/torch/venv3/pytorch/lib/python3.10/site-packages/torch/include -I/torch/venv3/pytorch/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/torch/venv3/pytorch/lib/python3.10/site-packages/torch/include/TH -I/torch/venv3/pytorch/lib/python3.10/site-packages/torch/include/THC -I/torch/venv3/pytorch/include -I/opt/py3.10/include/python3.10 -c -c /workspace/PARENet/pareconv/extensions/pybind.cpp -o /workspace/PARENet/build/temp.linux-x86_64-3.10/pareconv/extensions/pybind.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
In file included from /workspace/PARENet/pareconv/extensions/cpu/radius_neighbors/../../common/torch_helper.h:3:0,
                 from /workspace/PARENet/pareconv/extensions/cpu/radius_neighbors/radius_neighbors.h:3,
                 from /workspace/PARENet/pareconv/extensions/pybind.cpp:3:
/torch/venv3/pytorch/lib/python3.10/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include <cuda_runtime_api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
[6/6] c++ -MMD -MF /workspace/PARENet/build/temp.linux-x86_64-3.10/pareconv/extensions/cpu/radius_neighbors/radius_neighbors_cpu.o.d -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -fPIC -I/torch/venv3/pytorch/lib/python3.10/site-packages/torch/include -I/torch/venv3/pytorch/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/torch/venv3/pytorch/lib/python3.10/site-packages/torch/include/TH -I/torch/venv3/pytorch/lib/python3.10/site-packages/torch/include/THC -I/torch/venv3/pytorch/include -I/opt/py3.10/include/python3.10 -c -c /workspace/PARENet/pareconv/extensions/cpu/radius_neighbors/radius_neighbors_cpu.cpp -o /workspace/PARENet/build/temp.linux-x86_64-3.10/pareconv/extensions/cpu/radius_neighbors/radius_neighbors_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/torch/venv3/pytorch/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
    subprocess.run(
  File "/opt/py3.10/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1`
